languageCode: "en-us"
baseURL: https://petri-ojala-tieto.github.io/devops-gitops-demo/
title: "Tietoevry DevOps/GitOps process playground"
theme: "anubis"
paginate: 10
googleAnalytics: "G-12345"
enableRobotsTXT: true

menu:
  main:
  - identifier: All
    name: All
    title: All
    url: /content/
    weight: 0

params:
  author: "Tietoevry"
  email: petri.o.ojala@tietoevry.com 
  avatar: "/images/me.png" # used for microformats
  description: ""
  # Uncomment if you need this
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  # customCSS:
  #   - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "01-02-2006"
  paginationSinglePost: true
  style: light-without-switcher
  readMore: false # show read more button
  readNextPosts: 5  # show 5 related posts, 0 by default
  disableSummary: false
  copyCodeButton: true # true by default
  rssAsSocialIcon: true
  # utteranc.es support
  utterancesRepo: ""  # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  graphcommentId: ""
  webmentions:
    url: https://yourdomain.com/webemntions/receive
    login: hugo-theme-anubis
    pingback: true
  social:

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
